name: Lifesteal
main: JavierLeon9966\Lifesteal\Main
src-namespace-prefix: JavierLeon9966\Lifesteal
author: JavierLeon9966
version: 1.0.0
api: 4.0.0
description: You can steal hearts from the players you kill!
website: https://github.com/JavierLeon9966/Lifesteal